Upgrade to cargo 0.72
Cargo now supports strings for the debug config, but `cargo outdated`
needs to upgrade to support crates using that, or else it errors:

    $ cargo outdated
    error: failed to parse manifest at `[...]/Cargo.toml`

    Caused by:
      expected a boolean or an integer
      in `profile.dev.debug`